BitBucketURL='https://bitbucket.example.com'
authTokenBB='bitbucket auth token'
GiteaURL='https://gitea.example.com'
authTokenGitea='gitea auth token'
migrationUsername='user@example.com'
migrationPassword='password'
