BitbucketURL='https://api.bitbucket.org'
BitbucketWorkspace='your-workspace'
GiteaURL='https://gitea.example.com'
authTokenGitea='gitea auth token'
migrationUsername='user@example.com'
migrationPassword='password'
